name: Deploy Static Site to GitHub Pages

on:
  # Chạy khi có code push lên nhánh main
  push:
    branches: ["main"]

  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Cấp quyền GITHUB_TOKEN để deploy GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép một lần deploy chạy tại một thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job duy nhất: Deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Dấu chấm (.) nghĩa là upload toàn bộ thư mục gốc (chứa index.html)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
